//from clara's code: https://github.com/claraj/Java2545Examples/blob/main/src/main/java/week7_first_classes/tires/Tire.java

package org.example.week_7_object_oriented_programming.tire_comparison_vid_6;

public class Tire {
    //fields/variables/instances:

    private String name; //field
    private double price; //field
    private int warrantyMiles; //field

    //this vvv is the constructor (can be generated by Intellij), uses "this.name" structure
    public Tire(String name, double price, int warrantyMiles) {

        //here the object is "name" the field is "Tire" (name of the file)
        //the this.name is the name field, this.price is the price field, this.warrantyMiles
        // is the warrantyMiles field
        this.name  = name;
        this.price = price;
        this.warrantyMiles = warrantyMiles;
    }

    public double pricePer1000Miles() {
        /* Calculates price per 1000 miles, assuming the tire
        will last the number of miles it is warrantied for */
        return ( price / (double) warrantyMiles ) * 1000;
    }

    public double costForSet() {
        /* Returns how much 4 tires cost */
        return price * 4;
    }

    @Override
    public String toString() {
        return String.format("%s costs %.2f and has a warranty of %d miles. Cost per 1000 miles is $%.2f",
                name, price, warrantyMiles, pricePer1000Miles());
    }

}
